const swaggerAutogenConstructor = require("swagger-autogen");
const swaggerAutogen = swaggerAutogenConstructor();

const doc = {
  info: {
    version: "1.0.0",
    title: "Free Market",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header", // can be "header", "query" or "cookie"
      name: "X-API-KEY", // name of the header, query parameter or cookie
      description: "any description...",
    },
  },
  definitions: {
    clothesSchema: {
      canton: { type: String, required: true },
      city: { type: String, required: true },
      category: { type: String, required: true },
      condition: { type: String, required: true },
      title: { type: String, required: true },
      size: { type: String, required: true },
      detail: { type: String, required: true },
      contactTel: { type: String, required: false },
      contactEmail:{ type: String, required: false },
      photos: { type: Array, required: true },
    },
    electronicsSchema: {
      canton: { type: String, required: true },
      condition: { type: String, required: true },
      title: { type: String, required: true },
      detail: { type: String, required: true },
      contactTel: { type: String, required: false },
      contactEmail:{ type: String, required: false },
      photos: { type: Array, required: true },
      city: { type: String, required: true },
    },
    furnituresSchema: {
      canton: { type: String, required: true },
      condition: { type: String, required: true },
      title: { type: String, required: true },
      dimensions: { type: String, required: true },
      detail: { type: String, required: true },
      contactTel: { type: String, required: false },
      contactEmail:{ type: String, required: false },
      photos: { type: Array, required: true },
      city: { type: String, required: true },
    },
    wishSchema: {
      canton: { type: String, required: true },
      name: { type: String, required: true },
      title: { type: String, required: true },
      detail: { type: String, required: true },
      contactTel: { type: String, required: false },
      contactEmail:{ type: String, required: false },
      city: { type: String, required: false },
    },
    UsersSchema: {
      email: {
        type: String,
        required: true,
      },
      password: {
        type: String,
        required: true,
      },
    },
  },
};

const outputFile = "./swagger.json";
const endpointsFiles = ["./server.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("../server"); // Your project's root file
});
