const swaggerAutogenConstructor = require("swagger-autogen");
const swaggerAutogen = swaggerAutogenConstructor();

const doc = {
  info: {
    version: "1.0.0",
    title: "Free Market",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:8080",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header", // can be "header", "query" or "cookie"
      name: "X-API-KEY", // name of the header, query parameter or cookie
      description: "any description...",
    },
  },
  definitions: {
    UsersSchema: {
      userId: { type: String, required: true },
      email: { type: String, required: true },
      name: { type: String, required: false },
      birthDate: { type: Date, required: false },
      job: { type: String, required: false },
      detail: { type: String, required: false },
      canton: { type: String, required: false },
      city: { type: String, required: false },
      address: { type: String, required: false },
      contactNumber: { type: Number, required: false },
      photos: { type: Array, required: false },
    },
    EmailSchema: {
      name: { type: String, required: true },
      email: { type: String, required: true },
      title: { type: String, required: true },
      message: { type: String, required: true },
    },
    UsersSchema: {
      userId: { type: String, required: true },
      email: { type: String, required: true },
      name: { type: String, required: false },
      birthDate: { type: Date, required: false },
      job: { type: String, required: false },
      detail: { type: String, required: false },
      canton: { type: String, required: false },
      city: { type: String, required: false },
      address: { type: String, required: false },
      contactNumber: { type: Number, required: false },
      photos: { type: Array, required: false },
    },
    wishSchema: {
      mainCategory: { type: String, required: true },
      userId: { type: String, required: true },
      canton: { type: String, required: true },
      name: { type: String, required: true },
      title: { type: String, required: true },
      detail: { type: String, required: true },
      contactTel: { type: String, required: true },
      city: { type: String, required: true },
      photo: { type: String, required: false },
      contactEmail: { type: String, required: false },
    },
  },
};

const outputFile = "./swagger.json";
const endpointsFiles = ["./index.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("../index"); // Your project's root file
});
